version: '3'
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=editor
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db:
    driver: local
